=== prateekSth/Niney-Store/development/catalog_20048957.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="gift_card_store">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="store_detail" />
                <xs:element ref="store_menuBar" />
                <xs:element ref="gift_introduction" />
                <xs:element ref="offical_partner" />
                <xs:element ref="gift_card_text" />
                <xs:element ref="gift_cards" />
                <xs:element ref="steps" />
                <xs:element ref="store_footer" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="store_detail">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="store_information" />
                <xs:element ref="search_bar" />
                <xs:element ref="user_credentials" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="store_information">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="store_info" />
                <xs:element ref="gift_logo" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="store_info">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="owner" />
                <xs:element ref="location" />
                <xs:element ref="website" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="owner" type="xs:string" />
    <xs:element name="location" type="xs:string" />
    <xs:element name="website" type="xs:string" />

    <xs:element name="gift_logo">
        <xs:complexType>
            <xs:attribute ref="id" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="id" type="xs:string" />

    <xs:element name="search_bar" type="xs:string" />

    <xs:element name="user_credentials">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sign_up" />
                <xs:element ref="return" />
                <xs:element ref="login" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="sign_up" type="xs:string" />
    <xs:element name="return" type="xs:string" />
    <xs:element name="login" type="xs:string" />

    <xs:element name="store_menuBar">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="menu_list" maxOccurs="unbounded" minOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="menu_list" type="xs:string" />

    <xs:element name="gift_introduction">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gift_description" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="gift_description">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description_heading" />
                <xs:element ref="description_paragraph" />
                <xs:element ref="buyButton" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="description_heading" type="xs:string" />

    <xs:element name="description_paragraph" type="xs:string" />

    <xs:element name="buyButton" type="xs:string" />

    <xs:element name="offical_partner">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="partnersIntroduction" />
                <xs:element ref="partnersImages" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="partnersIntroduction" type="xs:string" />

    <xs:element name="partnersImages">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="partnersImage" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="partnersImage">
        <xs:complexType>
            <xs:attribute ref="id" />
        </xs:complexType>
    </xs:element>

    <xs:element name="gift_card_text">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gift_card_panel" />
                <xs:element ref="gift_card_label" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="gift_card_panel" type="xs:string" />
    <xs:element name="gift_card_label" type="xs:string" />

    <xs:element name="gift_cards">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gift_card" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="gift_card">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="image" />
                <xs:element ref="description" />
            </xs:sequence>
            <xs:attribute ref="giftID" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="giftID" type="xs:ID" />

    <xs:element name="image">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="card_image" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="card_image">
        <xs:complexType>
            <xs:attribute ref="id" />
        </xs:complexType>
    </xs:element>

    <xs:element name="description">
        <xs:complexType>
            <xs:all>
                <xs:element ref="name" />
                <xs:element ref="service_type" />
                <xs:element ref="cost" />
                <xs:element ref="digital_code" maxOccurs="1" minOccurs="0" />
                <xs:element ref="generated" />
                <xs:element ref="validity" />
                <xs:element ref="availability" />
                <xs:element ref="numbers_of_user" />
                <xs:element ref="discount" maxOccurs="1" minOccurs="0" />
                <xs:element ref="region" />
                <xs:element ref="manufacturer" />
                <xs:element ref="reloadable" maxOccurs="1" minOccurs="0" />
                <xs:element ref="refundable" maxOccurs="1" minOccurs="0" />
                <xs:element ref="numbers_of_user" maxOccurs="1" minOccurs="0" />
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="reloadable" type="xs:boolean" />
    <xs:element name="name">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="type" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Digital" />
                <xs:enumeration value="Physical" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="service_type">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="class" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="class" type="xs:string" />

    <xs:element name="cost">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="currency" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="currency" type="xs:string" />

    <xs:element name="digital_code" type="xs:string" />

    <xs:element name="generated" type="xs:date" />

    <xs:element name="validity" type="xs:string" />

    <xs:element name="availability" type="xs:positiveInteger" />

    <xs:element name="numbers_of_user">
        <xs:simpleType>
            <xs:restriction base="xs:positiveInteger">
                <xs:maxInclusive value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="discount" type="xs:decimal" />

    <xs:element name="region" type="xs:string" />

    <xs:element name="manufacturer">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="platform" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="platform" type="xs:string" />

    <xs:element name="refundable" type="xs:string" />

    <xs:element name="select_logo" type="xs:string" />
    <xs:element name="select_heading" type="xs:string" />
    <xs:element name="select_paragraph" type="xs:string" />
    <xs:element name="send_logo" type="xs:string" />
    <xs:element name="send_heading" type="xs:string" />
    <xs:element name="send_paragraph" type="xs:string" />
    <xs:element name="enjoy_logo" type="xs:string" />
    <xs:element name="enjoy_heading" type="xs:string" />
    <xs:element name="enjoy_paragraph" type="xs:string" />
    <xs:element name="item_select">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="select_logo" />
                <xs:element ref="select_heading" />
                <xs:element ref="select_paragraph" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="item_send">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="send_logo" />
                <xs:element ref="send_heading" />
                <xs:element ref="send_paragraph" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="item_enjoy">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="enjoy_logo" />
                <xs:element ref="enjoy_heading" />
                <xs:element ref="enjoy_paragraph" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="step_heading" type="xs:string" />
    <xs:element name="step_paragraph" type="xs:string" />
    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="item_select" />
                <xs:element ref="item_send" />
                <xs:element ref="item_enjoy" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="find_button" type="xs:string" />
    <xs:element name="steps">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="step_heading" />
                <xs:element ref="step_paragraph" />
                <xs:element ref="items" />
                <xs:element ref="find_button" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="region_name">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="id" use="optional" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="footer_image" type="xs:string" />
    <xs:element name="description_label" type="xs:string" />
    <xs:element name="locations">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="region_name" maxOccurs="unbounded" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="label" type="xs:string" />
    <xs:element name="product_panel" type="xs:string" />
    <xs:element name="product_label">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label" maxOccurs="unbounded" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="store_products">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="product_panel" />
                <xs:element ref="product_label" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="about_panel" type="xs:string" />
    <xs:element name="about_label">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label" maxOccurs="unbounded" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="store_about">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="about_panel" />
                <xs:element ref="about_label" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="info_panel" type="xs:string" />
    <xs:element name="info">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="id" use="optional" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="logo">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="id" use="optional" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="payment_panel" type="xs:string" />
    <xs:element name="payment_logo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="logo" maxOccurs="unbounded" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="contact_info">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="info_panel" />
                <xs:element ref="info" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="payment_option">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="payment_panel" />
                <xs:element ref="payment_logo" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="contact_container">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="contact_info" />
                <xs:element ref="payment_option" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="footer_container_description">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="footer_image" />
                <xs:element ref="description_label" />
                <xs:element ref="locations" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="footer_container_store_products">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="store_products" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="footer_container_store_about">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="store_about" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="footer_container_contact">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="contact_container" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="footer_container">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="footer_container_description" />
                <xs:element ref="footer_container_store_products" />
                <xs:element ref="footer_container_store_about" />
                <xs:element ref="footer_container_contact" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="store_footer">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="footer_container" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== prateekSth/Niney-Store/development/catalog_20048957.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="catalog_20048957.css" type="text/css"?>
<!-- 
    Name: Pratik Shrestha
    LondonMetID: 20048957
    Group: L2C3
    Store Name: Niney Gift Card Store
-->

<gift_card_store xsi:noNamespaceSchemaLocation="catalog_20048957.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <store_detail>
        <store_information>
            <store_info>
                <owner>NINEY</owner>
                <location>Enfield, London</location>
                <website> www.giftstore.com.uk</website>
            </store_info>
            <gift_logo id="gift" />
        </store_information>
        <search_bar>Search for Brand and Product</search_bar>
        <user_credentials>
            <sign_up>Sign In </sign_up>
            <return>Return  &#38; Orders</return>
            <login>Log In</login>
        </user_credentials>
    </store_detail>

    <store_menuBar>
        <menu_list>Home</menu_list>
        <menu_list>Software</menu_list>
        <menu_list>Gift card</menu_list>
        <menu_list>Game card</menu_list>
        <menu_list>Deals</menu_list>
        <menu_list>Promo</menu_list>
    </store_menuBar>

    <gift_introduction>
        <gift_description>
            <description_heading>
                <![CDATA[Buy and Send Gift Cards Instantly]]>
            </description_heading>
            <description_paragraph>
                <![CDATA[Buy premium gift cards and send by email, text, or hand deliver.]]>
            </description_paragraph>
            <buyButton>Buy gift card</buyButton>
        </gift_description>
    </gift_introduction>

    <offical_partner>
        <partnersIntroduction>
            <![CDATA[Our Official Sponsors and partners]]>
        </partnersIntroduction>
        <partnersImages>
            <partnersImage id="amazonImage"></partnersImage>
            <partnersImage id="googleImage"></partnersImage>
            <partnersImage id="microsoftImage"></partnersImage>
            <partnersImage id="spotifyImage"></partnersImage>
            <partnersImage id="appleImage"></partnersImage>
            <partnersImage id="netflixImage"></partnersImage>
            <partnersImage id="itunesImage"></partnersImage>
            <partnersImage id="xboxImage"></partnersImage>
            <partnersImage id="tensentImage"></partnersImage>
        </partnersImages>
    </offical_partner>

    <gift_card_text>
        <gift_card_panel>Shop from Hundreds of Gift Cards</gift_card_panel>
        <gift_card_label>Buy, Send and Claim Gift Cards. Chip in with Friends. Store and Manage Gift Cards.</gift_card_label>
    </gift_card_text>

    <gift_cards>
        <gift_card giftID="gID1">
            <image>
                <card_image id="netflix"></card_image>
            </image>
            <description>
                <name type="Digital">Netflix</name>
                <service_type class="subscription">Streaming service</service_type>
                <cost currency="USD">50</cost>
                <digital_code>G9#####</digital_code>
                <generated>2021-09-20</generated>
                <validity>Upto 6 months</validity>
                <availability>10</availability>
                <numbers_of_user>4</numbers_of_user>
                <discount>5</discount>
                <region>Global</region>
                <manufacturer platform="video streaming">Netflix</manufacturer>
                <refundable>1 Day return</refundable>
            </description>
        </gift_card>
        <gift_card giftID="gID2">
            <image>
                <card_image id="spotify"></card_image>
            </image>
            <description>
                <name type="Physical">Spotify</name>
                <service_type class="subscription">Audio streaming service</service_type>
                <cost currency="USD">105</cost>
                <generated>2021-07-10</generated>
                <validity>Upto 12 months</validity>
                <availability>12</availability>
                <numbers_of_user>4</numbers_of_user>
                <region>Global</region>
                <manufacturer platform="Audio streaming">Spotify</manufacturer>
                <reloadable>true</reloadable>
                <refundable>2 Day return</refundable>
            </description>
        </gift_card>

        <gift_card giftID="gID3">
            <image>
                <card_image id="amazon"></card_image>
            </image>
            <description>
                <name type="Digital">Amazon prime</name>
                <service_type class="subscription">Streaming service</service_type>
                <cost currency="USD">100</cost>
                <digital_code>AP9#####</digital_code>
                <generated>2021-06-20</generated>
                <validity>Upto 4 months</validity>
                <availability>19</availability>
                <numbers_of_user>4</numbers_of_user>
                <discount>6</discount>
                <region>Global</region>
                <manufacturer platform="video streaming">Amazon </manufacturer>
                <refundable>2 Day return</refundable>
            </description>
        </gift_card>
        <gift_card giftID="gID4">
            <image>
                <card_image id="itunes"></card_image>
            </image>
            <description>
                <name type="Digital">i-Tunes</name>
                <service_type class="subscription">Audio Streaming service</service_type>
                <cost currency="USD">100</cost>
                <digital_code> iT3#####</digital_code>
                <generated> 2021-12-12</generated>
                <availability>19</availability>
                <validity>Upto 6 months</validity>
                <numbers_of_user> 4</numbers_of_user>
                <discount>5</discount>
                <region>Global</region>
                <manufacturer platform="audio streaming"> Netflix</manufacturer>
                <refundable> 1 Day return</refundable>
            </description>
        </gift_card>
        <gift_card giftID="gID5">
            <image>
                <card_image id="pubg"></card_image>
            </image>
            <description>
                <name type="Digital">PUBG</name>
                <service_type class="subscription">Gaming service</service_type>
                <cost currency="USD">50</cost>
                <digital_code>p12#####</digital_code>
                <generated>2021-07-25</generated>
                <validity>unlimited</validity>
                <availability>26</availability>
                <numbers_of_user>1</numbers_of_user>
                <region>Global</region>
                <manufacturer platform="gaming platform">tencent</manufacturer>
                <refundable>1 Day return</refundable>
            </description>
        </gift_card>
        <gift_card giftID="gID6">
            <image>
                <card_image id="ps4"></card_image>
            </image>
            <description>
                <name type="Digital">PS-4</name>
                <service_type class="subscription">Gaming service</service_type>
                <cost currency="USD">100</cost>
                <digital_code>PS1#####</digital_code>
                <generated>2022-02-21</generated>
                <validity>Upto 6 months</validity>
                <availability>10</availability>
                <numbers_of_user>4</numbers_of_user>
                <discount>5</discount>
                <region>Global</region>
                <manufacturer platform="gaming platform">Netflix</manufacturer>
                <refundable>1 Day return</refundable>
            </description>
        </gift_card>
        <gift_card giftID="gID7">
            <image>
                <card_image id="leagueoflegend"></card_image>
            </image>
            <description>
                <name type="Digital">leagueoflegend</name>
                <service_type class="subscription">Gaming service</service_type>
                <cost currency="USD"> $25</cost>
                <digital_code>LOL2#####</digital_code>
                <generated>2021-09-15</generated>
                <validity>unlimited</validity>
                <availability>3</availability>
                <numbers_of_user>1</numbers_of_user>
                <region>Global</region>
                <manufacturer platform="gaming platform">Riot Games Corporation</manufacturer>
                <refundable>1 Day return</refundable>
            </description>
        </gift_card>
        <gift_card giftID="gID8">
            <image>
                <card_image id="roblox"></card_image>
            </image>
            <description>
                <name type="Digital">Roblox</name>
                <service_type class="subscription">Gaming service</service_type>
                <cost currency="USD"> $20</cost>
                <digital_code>R02#####</digital_code>
                <generated>2021-04-15</generated>
                <validity>unlimited</validity>
                <availability>29</availability>
                <numbers_of_user>1</numbers_of_user>
                <region>Global</region>
                <manufacturer platform="gaming platform">Roblox Corporation</manufacturer>
                <refundable>1 Day return</refundable>
            </description>
        </gift_card>
        <gift_card giftID="gID9">
            <image>
                <card_image id="office365"></card_image>
            </image>
            <description>
                <name type="Physical">Netflix</name>
                <service_type class="subscription">Streaming service</service_type>
                <cost currency="USD">125</cost>
